#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Email-Store-Thread
version:      1.0
version_from: lib/Email/Store/Thread.pm
installdirs:  site
requires:
    Mail::Thread:                  2.5
    Email::Store:                  0
    Email::Folder:                 0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.12
